---
title: "2nd_draft"
author: "Xuechun Lu, Yuting Wen, Peter Han, Yuetong Liu"
date: "15/03/2020"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
libraries
```{r, message=F, warning=F}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(here)
library(readxl)
library(broom)
library(glmnet)
library(dummies)
```

1. data processing
```{r, warning=F, message=F}
## Aggregated Data
assessment_aggregate <- read.csv(here("data","assessment_aggregate.csv"))[,-1]
#assessment_2020 <- read.csv(here("data","assessment_2020.csv"))[,-1]
#assessment_2020.full <- read_excel(here("data/Assessment", "2020 Only.xlsx"))
```

2. Test correlations between past mill rates and other features.
```{r}
# ______________________________________________________________________________________________
# CONTINUS variables
assessment_transform <- assessment_aggregate

# log transformation and take avg
assessment_transform[,9] <- assessment_transform$assessTotal/assessment_transform$propertyCount
names(assessment_transform)[9] <- paste("AvgTotalAssessmentValue")
assessment_transform[,10] <- assessment_transform$landTotal/assessment_transform$propertyCount
names(assessment_transform)[10] <- paste("AvgTotalLandValue")
assessment_transform[,11] <- assessment_transform$improvementTotal/assessment_transform$propertyCount
names(assessment_transform)[11] <- paste("AvgTotalImprovementValue")

cor(assessment_transform$rate,assessment_transform$AvgTotalAssessmentValue)
cor(assessment_transform$rate,assessment_transform$AvgTotalLandValue)
cor(assessment_transform$rate,assessment_transform$AvgTotalImprovementValue)

assessment_transform %>%
                   ggplot(aes(x=AvgTotalAssessmentValue,
                              y=rate,group=AddressAssessorMunicipalityDesc,
                              color=AddressAssessorMunicipalityDesc)) + 
                   geom_point() + 
                   ggtitle(sprintf("mill rate vs average total assessment value")) + 
                   geom_smooth(aes(group = 1), size = 0.5, method = "lm", se = FALSE, colour = "black")

assessment_transform %>%
                   ggplot(aes(x=AvgTotalLandValue,
                              y=rate,group=AddressAssessorMunicipalityDesc,
                              color=AddressAssessorMunicipalityDesc)) + 
                   geom_point() + 
                   ggtitle(sprintf("mill rate vs average total land value")) + 
                   geom_smooth(aes(group = 1), size = 0.5, method = "lm", se = FALSE, colour = "black")

assessment_transform %>%
                   ggplot(aes(x=AvgTotalImprovementValue,
                              y=rate,group=AddressAssessorMunicipalityDesc,
                              color=AddressAssessorMunicipalityDesc)) + 
                   geom_point() + 
                   ggtitle(sprintf("mill rate vs average total improvement value")) + 
                   geom_smooth(aes(group = 1), size = 0.5, method = "lm", se = FALSE, colour = "black")

# ______________________________________________________________________________________________
# CATEGORICAL variables
for(i in colnames(assessment_transform)[2:3]){
  print(ggplot(assessment_aggregate, aes(x=as.factor(!!as.name(i)),y=rate, fill=as.factor(!!as.name(i)))) + 
  geom_boxplot()+ 
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none"))
}

# kruskal.test
kruskal.test(assessment_transform$rate~assessment_transform$TaxClassCode,data=assessment_transform)
kruskal.test(assessment_transform$rate~assessment_transform$AddressAssessorMunicipalityDesc,data=assessment_transform)
```


3.model fitting

```{r, warning=FALSE}
dummy_municipal<-dummy(assessment_transform$AddressAssessorMunicipalityDesc)
dummy_taxclass<-dummy(assessment_transform$TaxClassCode)
# build x matrix
x<-cbind(dummy_municipal,dummy_taxclass,assessment_transform$AvgTotalAssessmentValue)
y<-assessment_transform$rate
x<-cbind(x,y)
# correct col name
#assessTotal,assessment_aggregate$landTotal,assessment_aggregate$improvementTotal,assessment_aggregate$propertyCount,assessment_aggregate$tax
colnames(x)[26]<-c("AvgTotalAssessmentValue")
colnames(x)[27]<-c("rate")
xm<-x[,1:(ncol(x)-1)]
x.data.frame<-assessment_transform
xm.data.frame<-assessment_transform[,-c(1,8,9,10,11)]
y.data.frame<-assessment_transform$rate
n <- nrow(xm)
k <- 10
ii <- (1:n)%%k + 1
set.seed(123)
N <- 50
mspe1.n<-mspe1.el<-mspe1.la <- mspe1.f <- mspe1.ri <- mspe1.reduced <- rep(0, N)
mspe.n<-mspe.el<-mspe.la <- mspe.f <- mspe.ri <- mspe.reduced <- rep(0, N)
for (i in 1:N) {
  ii <- sample(ii)
  pr1.n<-pr1.el<-pr1.la <- pr1.f <- pr1.ri <- pr1.reduced <- rep(0, n)
  pr.n<-pr.el<-pr.la <- pr.f <- pr.ri <- pr.reduced <- rep(0, n)
  for (j in 1:k) {
    # ~ models trained!
    tmp.ri <- cv.glmnet(x = xm[ii != j, ], y = y[ii != j], lambda = lambdas, 
                        nfolds = 10, alpha = 0, family = "gaussian")
    tmp.la <- cv.glmnet(x = xm[ii != j, ], y = y[ii != j], lambda = lambdas, 
                        nfolds = 10, alpha = 1, family = "gaussian")
    tmp.reduced <- lm(rate ~ factor(TaxClassCode)+factor(AddressAssessorMunicipalityDesc)+AvgTotalAssessmentValue, 
                      data = x.data.frame[ii != j, ])
    tmp.full <- lm(rate ~ factor(AddressAssessorMunicipalityDesc)+factor(TaxClassCode)+assessTotal+landTotal+improvementTotal+propertyCount, 
                   data = x.data.frame[ii != j, ])
    # tmp.n<-lm(rate ~ 1, data = x.data.frame[ii != j, ])
    
    # tmp.elastic<-train(
    #   rate~factor(AddressAssessorMunicipalityDesc)+factor(TaxClassCode)+AvgTotalAssessmentValue,
    #   data = x.data.frame[ii != j, ],
    #   method = "glmnet",
    #   trControl = cv_10)
    
    # ~ prediction vector on train set
    pr1.ri[ii != j] <- predict(tmp.ri, s = tmp.ri$lambda.min, newx = xm[ii !=
                                                                         j, ])
    pr1.la[ii != j] <- predict(tmp.la, s = tmp.la$lambda.min, newx = xm[ii !=
                                                                         j, ])
    pr1.reduced[ii != j] <- predict(tmp.reduced, newdata = x.data.frame[ii != j, ])
    pr1.f[ii != j] <- predict(tmp.full, newdata = x.data.frame[ii != j, ])
    # pr1.n[ii != j] <- predict(tmp.n, newdata = x.data.frame[ii != j, ])

    # index<-which.min(tmp.elastic$results$RMSE)
    # pr1.el[ii != j] <- predict(tmp.elastic,
    #                           alpha = tmp.elastic$results[index,1],
    #                           lambda = tmp.elastic$results[index,2],
    #                           newdata = xm.data.frame[ii == j, ])
    
    # ~ prediction vector on test set
    pr.ri[ii == j] <- predict(tmp.ri, s = tmp.ri$lambda.min, newx = xm[ii == 
                                                                         j, ])
    pr.la[ii == j] <- predict(tmp.la, s = tmp.la$lambda.min, newx = xm[ii == 
                                                                         j, ])
    pr.reduced[ii == j] <- predict(tmp.reduced, newdata = x.data.frame[ii == j, ])
    pr.f[ii == j] <- predict(tmp.full, newdata = x.data.frame[ii == j, ])
    # pr.n[ii == j] <- predict(tmp.n, newdata = x.data.frame[ii == j, ])
    # index<-which.min(tmp.elastic$results$RMSE)
    # pr.el[ii == j] <- predict(tmp.elastic,
    #                           alpha = tmp.elastic$results[index,1],
    #                           lambda = tmp.elastic$results[index,2],
    #                           newdata = xm.data.frame[ii == j, ])
  }
  
  # goodness of fit
  mspe1.ri[i]<-mean((y - pr1.ri)^2)
  mspe1.la[i]<-mean((y - pr1.la)^2)
  mspe1.reduced[i]<-mean((y - pr1.reduced)^2)
  mspe1.f[i]<-mean((y - pr1.f)^2)
  # mspe1.n[i]<-mean((y - pr1.n)^2)
  # mspe1.el[i]<-mean((y - pr1.el)^2)
  
  # prediction power
  mspe.ri[i]<-mean((y - pr.ri)^2)
  mspe.la[i]<-mean((y - pr.la)^2)
  mspe.reduced[i]<-mean((y - pr.reduced)^2)
  mspe.f[i]<-mean((y - pr.f)^2)
  # mspe.n[i]<-mean((y - pr.n)^2)
  # mspe.el[i]<-mean((y - pr.el)^2)
  
  
}


boxplot(mspe1.la, 
        mspe1.ri,
        # mspe1.el, 
        # mspe1.n, 
        mspe1.reduced, 
        mspe1.f, 
        names = c("LASSO", 
                  "Ridge", 
                  # "Elastic Net", 
                  "Reduced", 
                  "Full"), 
        col = c("steelblue","gray80",
                # "pink", 
                "tomato", "springgreen"), 
        cex.axis = 1, 
        cex.lab = 1, 
        cex.main = 2,
        main = "Goodness of Fit",
        ylab = expression(hat(MSE)))

boxplot(mspe.la, 
        mspe.ri,
        # mspe.el, 
        # mspe.n, 
        mspe.reduced, 
        mspe.f, 
        names = c("LASSO", "Ridge", 
                  # "Elastic Net", 
                  "Reduced", "Full"), 
        col = c("steelblue","gray80",
                # "pink", 
                "tomato", "springgreen"), 
        cex.axis = 1, 
        cex.lab = 1, 
        cex.main = 2,
        main = "Prediction Power",
        ylab = expression(hat(MSPE)))



```

```{r fit}
## choose full model
linear_1<-lm(rate~factor(AddressAssessorMunicipalityDesc)+factor(TaxClassCode)+AvgTotalAssessmentValue,data=assessment_aggregate)

## Fit and get PMSE
assessment_2020.agg <- assessment_2020%>%
  mutate(predict_rate = predict(linear_1,newdata = .))
resid<-assessment_2020.agg$predict_rate - assessment_2020.agg$rate
sqrt(sum(resid^2)/nrow(assessment_2020.agg))


## Final result
municipality.list = c(
  "Burnaby", 
  "Coquitlam", 
  "Delta", 
  "Langley - City", 
  "Langley - Township",
  "Maple Ridge",
  "Maple Ridge Rural", 
  "North Vancouver - City",
  "North Vancouver - Dist",
  "Pitt Meadows", 
  "Port Coquitlam", 
  "Port Moody", 
  "Richmond", 
  "Surrey", 
  "Vancouver", 
  "White Rock", 
  "West Vancouver", 
  "Bowen Island", 
  "Anmore", 
  "Belcarra",
  "Lions Bay",
  "New Westminster")

## Raw Data
a <- assessment_2020.full%>%
  filter(TaxClassCode %in% c("01","05","06"),
         AddressAssessorMunicipalityDesc %in% municipality.list)

## Aggregate Data
b <- assessment_2020.agg%>%
  select(-c(Year, assessTotal : rate))%>%
  mutate(TaxClassCode = as.factor(paste0("0",TaxClassCode)))

assessment_2020.final<- merge(a, b, by =c("AddressAssessorMunicipalityDesc", "TaxClassCode"), all.x = TRUE)

write.csv(assessment_2020.final, "../Data/Assessment/assessment_2020.final")
write.csv(b, "../Data/assessment_2020.csv")
```

